### PR TITLE
ISSUE 3 : fix 

### PR DESCRIPTION
**Pull request by anooppoommen**
the error was caused for the code rendering since not all 
markdown had the language name set in it

as in this sample file
https://colab.research.google.com/notebooks/welcome.ipynb

### CODE REVIEW

**Comment by clemens-tolboom** [comment]
The bug fix is 4 lines; the PR contains ~3000 changes ... huh!?

Did you make a push mistake adding lot's of formatting and .lock file?

**Comment by clemens-tolboom** [comment]
Very quick response :-)

What I meant was to only commit the file `src/notebookjs/notebook.js` as that contains your fix. Other changed files are codestyle (whitespace) IIRC.

Too make it easier for maintainers I would do

- `git pull origin master` # repo of jithurjacob
- `git checkout -b feature/name-undefined`
- `git push nooppoommen feature/name-undefined --set-upstream`
- create a new PR

The above is kinda gitflow.

Let's hope @jithurjacob picks up this soon too :-)
Hope this helps and is not to offensive :-p

**Comment by anooppoommen** [comment]
@clemens-tolboom thanks for the tip and no it was not that oppressive it's actually really helpfull 😁😁

**Comment by SylEze** [comment]
Any news ?

**Comment by clemens-tolboom** [comment]
@SylEze you can create a new PR from the changes done on src/notebookjs/notebook.js only if you like.

**Comment by clemens-tolboom** [comment]
@anooppoommen I just edited the file through the github UI thus created PR #15. Thanks for your contribution. Please review #15 if you have time.

**Pull request closed without merging**
